# Generated by Django 5.2.7 on 2025-10-14 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mno', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=20)),
                ('profile', models.ImageField(default='', upload_to='')),
                ('usertype', models.CharField(default='pateint', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cchoice', models.CharField(choices=[('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Surgeon', 'Surgeon'), ('Immunology', 'Immunology')], max_length=20)),
                ('dname', models.CharField(max_length=20)),
                ('demail', models.EmailField(max_length=254, unique=True)),
                ('qfc', models.CharField(max_length=40)),
                ('charges', models.IntegerField()),
                ('address', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exp', models.IntegerField()),
                ('dimage', models.ImageField(default='', upload_to='doctor/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
