# Generated by Django 5.2.6 on 2025-11-01 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pemail', models.EmailField(max_length=254, unique=True)),
                ('pmno', models.BigIntegerField(unique=True)),
                ('paddress', models.TextField()),
                ('age', models.PositiveIntegerField(unique=True)),
                ('gender', models.CharField()),
                ('date', models.DateField()),
                ('symptoms', models.CharField(max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
