# Generated by Django 5.2.6 on 2025-11-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pemail',
            field=models.EmailField(max_length=254),
        ),
    ]
