# Generated by Django 5.2.6 on 2025-11-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_patient_pemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pmno',
            field=models.BigIntegerField(),
        ),
    ]
