# Generated by Django 5.2.5 on 2025-11-06 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_patient_pmno'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='time',
            field=models.TimeField(default=datetime.time(15, 34, 29, 936705)),
            preserve_default=False,
        ),
    ]
