# Generated by Django 5.2.5 on 2025-11-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_patient_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dimage',
            field=models.ImageField(blank=True, null=True, upload_to='doctor/'),
        ),
    ]
