# Generated by Django 5.2.5 on 2025-11-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_profile_user_image_alter_doctor_dimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pemail',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pmno',
        ),
    ]
