# Generated by Django 5.2.5 on 2025-11-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_patient_pemail_remove_patient_pmno'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default=9, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='mno',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
