# Generated by Django 5.2.5 on 2025-11-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='category',
            field=models.CharField(choices=[('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Surgeon', 'Surgeon'), ('Immunology', 'Immunology')], default='Dermatologist', max_length=20),
        ),
    ]
