# Generated by Django 5.2.5 on 2025-11-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_patient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
