# Generated by Django 5.2.6 on 2026-03-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followercount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followercount',
            old_name='follwer',
            new_name='follower',
        ),
    ]
