# Generated by Django 6.0.2 on 2026-02-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='machine_qr/'),
        ),
    ]
